import { FacebookIcon, TwitterIcon, Linkedin, InstagramIcon } from "lucide-react";

export const ORGANIZATION_CATEGORIES = [
  { id: 1, value: "ENTERPRISE", label: "Enterprise" },
  { id: 2, value: "SME", label: "Small and Medium Enterprises (SME)" },
  { id: 3, value: "STARTUP", label: "Startup" },
  { id: 4, value: "NPO", label: "Non Profit Organization (NPO)" },
  { id: 5, value: "GOVERNMENT", label: "Government" },
  { id: 6, value: "EDUCATION", label: "Educational Institution" },
  { id: 7, value: "CORPORATION", label: "Corporation" },
  { id: 8, value: "PARTNERSHIP", label: "Partnership" },
  { id: 9, value: "SOLE_PROPRIETORSHIP", label: "Sole Proprietorship" },
  { id: 10, value: "COOPERATIVE", label: "Cooperative" },
  { id: 11, value: "MNC", label: "Multinational Corporation (MNC)" },
  { id: 12, value: "PSU", label: "Public Sector Unit (PSU)" },
  { id: 13, value: "SOCIAL_ENTERPRISE", label: "Social Enterprise" },
  { id: 14, value: "FRANCHISE", label: "Franchise" },
  { id: 15, value: "FAMILY_BUSINESS", label: "Family Business" },
  { id: 16, value: "PROFESSIONAL_ASSOCIATION", label: "Professional Association" },
  { id: 17, value: "RELIGIOUS_ORGANIZATION", label: "Religious Organization" },
  { id: 18, value: "CHARITY", label: "Charity" },
  { id: 19, value: "TRUST", label: "Trust" },
  { id: 20, value: "FOUNDATION", label: "Foundation" },
  { id: 21, value: "PUBLIC_COMPANY", label: "Public Company" },
  { id: 22, value: "PRIVATE_COMPANY", label: "Private Company" },
  { id: 23, value: "B_CORP", label: "B Corporation (Benefit Corporation)" },
  { id: 24, value: "LLC", label: "Limited Liability Company (LLC)" },
  { id: 25, value: "JOINT_VENTURE", label: "Joint Venture" },
  { id: 26, value: "HOLDING_COMPANY", label: "Holding Company" },
  { id: 27, value: "CONSORTIUM", label: "Consortium" },
  { id: 28, value: "THINK_TANK", label: "Think Tank" },
  { id: 29, value: "RESEARCH_INSTITUTION", label: "Research Institution" },
  { id: 30, value: "HEALTHCARE_PROVIDER", label: "Healthcare Provider" },
  { id: 31, value: "BANKING_FINANCIAL_INSTITUTION", label: "Banking/Financial Institution" },
  { id: 32, value: "TRADE_UNION", label: "Trade Union" },
  { id: 33, value: "ADVOCACY_GROUP", label: "Advocacy Group" },
  { id: 34, value: "COMMUNITY_ORGANIZATION", label: "Community Organization" },
  { id: 35, value: "NGO", label: "Non Governmental Organization (NGO)" },
] as const;

export const COUNTRIES = [
  { id: 1, label: "Afghanistan", value: "AF" },
  { id: 2, label: "Albania", value: "AL" },
  { id: 3, label: "Algeria", value: "DZ" },
  { id: 4, label: "Andorra", value: "AD" },
  { id: 5, label: "Angola", value: "AO" },
  { id: 6, label: "Antigua and Barbuda", value: "AG" },
  { id: 7, label: "Argentina", value: "AR" },
  { id: 8, label: "Armenia", value: "AM" },
  { id: 9, label: "Australia", value: "AU" },
  { id: 10, label: "Austria", value: "AT" },
  { id: 11, label: "Azerbaijan", value: "AZ" },
  { id: 12, label: "Bahamas", value: "BS" },
  { id: 13, label: "Bahrain", value: "BH" },
  { id: 14, label: "Bangladesh", value: "BD" },
  { id: 15, label: "Barbados", value: "BB" },
  { id: 16, label: "Belarus", value: "BY" },
  { id: 17, label: "Belgium", value: "BE" },
  { id: 18, label: "Belize", value: "BZ" },
  { id: 19, label: "Benin", value: "BJ" },
  { id: 20, label: "Bhutan", value: "BT" },
  { id: 21, label: "Bolivia", value: "BO" },
  { id: 22, label: "Bosnia and Herzegovina", value: "BA" },
  { id: 23, label: "Botswana", value: "BW" },
  { id: 24, label: "Brazil", value: "BR" },
  { id: 25, label: "Brunei", value: "BN" },
  { id: 26, label: "Bulgaria", value: "BG" },
  { id: 27, label: "Burkina Faso", value: "BF" },
  { id: 28, label: "Burundi", value: "BI" },
  { id: 29, label: "Cabo Verde", value: "CV" },
  { id: 30, label: "Cambodia", value: "KH" },
  { id: 31, label: "Cameroon", value: "CM" },
  { id: 32, label: "Canada", value: "CA" },
  { id: 33, label: "Central African Republic", value: "CF" },
  { id: 34, label: "Chad", value: "TD" },
  { id: 35, label: "Chile", value: "CL" },
  { id: 36, label: "China", value: "CN" },
  { id: 37, label: "Colombia", value: "CO" },
  { id: 38, label: "Comoros", value: "KM" },
  { id: 39, label: "Congo (Congo-Brazzaville)", value: "CG" },
  { id: 40, label: "Congo (DRC)", value: "CD" },
  { id: 41, label: "Costa Rica", value: "CR" },
  { id: 42, label: "Croatia", value: "HR" },
  { id: 43, label: "Cuba", value: "CU" },
  { id: 44, label: "Cyprus", value: "CY" },
  { id: 45, label: "Czechia", value: "CZ" },
  { id: 46, label: "Denmark", value: "DK" },
  { id: 47, label: "Djibouti", value: "DJ" },
  { id: 48, label: "Dominica", value: "DM" },
  { id: 49, label: "Dominican Republic", value: "DO" },
  { id: 50, label: "Ecuador", value: "EC" },
  { id: 51, label: "Egypt", value: "EG" },
  { id: 52, label: "El Salvador", value: "SV" },
  { id: 53, label: "Equatorial Guinea", value: "GQ" },
  { id: 54, label: "Eritrea", value: "ER" },
  { id: 55, label: "Estonia", value: "EE" },
  { id: 56, label: "Eswatini", value: "SZ" },
  { id: 57, label: "Ethiopia", value: "ET" },
  { id: 58, label: "Fiji", value: "FJ" },
  { id: 59, label: "Finland", value: "FI" },
  { id: 60, label: "France", value: "FR" },
  { id: 61, label: "Gabon", value: "GA" },
  { id: 62, label: "Gambia", value: "GM" },
  { id: 63, label: "Georgia", value: "GE" },
  { id: 64, label: "Germany", value: "DE" },
  { id: 65, label: "Ghana", value: "GH" },
  { id: 66, label: "Greece", value: "GR" },
  { id: 67, label: "Grenada", value: "GD" },
  { id: 68, label: "Guatemala", value: "GT" },
  { id: 69, label: "Guinea", value: "GN" },
  { id: 70, label: "Guinea-Bissau", value: "GW" },
  { id: 71, label: "Guyana", value: "GY" },
  { id: 72, label: "Haiti", value: "HT" },
  { id: 73, label: "Honduras", value: "HN" },
  { id: 74, label: "Hungary", value: "HU" },
  { id: 75, label: "Iceland", value: "IS" },
  { id: 76, label: "India", value: "IN" },
  { id: 77, label: "Indonesia", value: "ID" },
  { id: 78, label: "Iran", value: "IR" },
  { id: 79, label: "Iraq", value: "IQ" },
  { id: 80, label: "Ireland", value: "IE" },
  { id: 81, label: "Israel", value: "IL" },
  { id: 82, label: "Italy", value: "IT" },
  { id: 83, label: "Jamaica", value: "JM" },
  { id: 84, label: "Japan", value: "JP" },
  { id: 85, label: "Jordan", value: "JO" },
  { id: 86, label: "Kazakhstan", value: "KZ" },
  { id: 87, label: "Kenya", value: "KE" },
  { id: 88, label: "Kiribati", value: "KI" },
  { id: 89, label: "Korea (North)", value: "KP" },
  { id: 90, label: "Korea (South)", value: "KR" },
  { id: 91, label: "Kuwait", value: "KW" },
  { id: 92, label: "Kyrgyzstan", value: "KG" },
  { id: 93, label: "Laos", value: "LA" },
  { id: 94, label: "Latvia", value: "LV" },
  { id: 95, label: "Lebanon", value: "LB" },
  { id: 96, label: "Lesotho", value: "LS" },
  { id: 97, label: "Liberia", value: "LR" },
  { id: 98, label: "Libya", value: "LY" },
  { id: 99, label: "Liechtenstein", value: "LI" },
  { id: 100, label: "Lithuania", value: "LT" },
  { id: 101, label: "Luxembourg", value: "LU" },
  { id: 102, label: "Madagascar", value: "MG" },
  { id: 103, label: "Malawi", value: "MW" },
  { id: 104, label: "Malaysia", value: "MY" },
  { id: 105, label: "Maldives", value: "MV" },
  { id: 106, label: "Mali", value: "ML" },
  { id: 107, label: "Malta", value: "MT" },
  { id: 108, label: "Marshall Islands", value: "MH" },
  { id: 109, label: "Mauritania", value: "MR" },
  { id: 110, label: "Mauritius", value: "MU" },
  { id: 111, label: "Mexico", value: "MX" },
  { id: 112, label: "Micronesia", value: "FM" },
  { id: 113, label: "Moldova", value: "MD" },
  { id: 114, label: "Monaco", value: "MC" },
  { id: 115, label: "Mongolia", value: "MN" },
  { id: 116, label: "Montenegro", value: "ME" },
  { id: 117, label: "Morocco", value: "MA" },
  { id: 118, label: "Mozambique", value: "MZ" },
  { id: 119, label: "Myanmar", value: "MM" },
  { id: 120, label: "Namibia", value: "NA" },
  { id: 121, label: "Nauru", value: "NR" },
  { id: 122, label: "Nepal", value: "NP" },
  { id: 123, label: "Netherlands", value: "NL" },
  { id: 124, label: "New Zealand", value: "NZ" },
  { id: 125, label: "Nicaragua", value: "NI" },
  { id: 126, label: "Niger", value: "NE" },
  { id: 127, label: "Nigeria", value: "NG" },
  { id: 128, label: "North Macedonia", value: "MK" },
  { id: 129, label: "Norway", value: "NO" },
  { id: 130, label: "Oman", value: "OM" },
  { id: 131, label: "Pakistan", value: "PK" },
  { id: 132, label: "Palau", value: "PW" },
  { id: 133, label: "Panama", value: "PA" },
  { id: 134, label: "Papua New Guinea", value: "PG" },
  { id: 135, label: "Paraguay", value: "PY" },
  { id: 136, label: "Peru", value: "PE" },
  { id: 137, label: "Philippines", value: "PH" },
  { id: 138, label: "Poland", value: "PL" },
  { id: 139, label: "Portugal", value: "PT" },
  { id: 140, label: "Qatar", value: "QA" },
  { id: 141, label: "Romania", value: "RO" },
  { id: 142, label: "Russia", value: "RU" },
  { id: 143, label: "Rwanda", value: "RW" },
  { id: 144, label: "Saint Kitts and Nevis", value: "KN" },
  { id: 145, label: "Saint Lucia", value: "LC" },
  { id: 146, label: "Saint Vincent and the Grenadines", value: "VC" },
  { id: 147, label: "Samoa", value: "WS" },
  { id: 148, label: "San Marino", value: "SM" },
  { id: 149, label: "Sao Tome and Principe", value: "ST" },
  { id: 150, label: "Saudi Arabia", value: "SA" },
  { id: 151, label: "Senegal", value: "SN" },
  { id: 152, label: "Serbia", value: "RS" },
  { id: 153, label: "Seychelles", value: "SC" },
  { id: 154, label: "Sierra Leone", value: "SL" },
  { id: 155, label: "Singapore", value: "SG" },
  { id: 156, label: "Slovakia", value: "SK" },
  { id: 157, label: "Slovenia", value: "SI" },
  { id: 158, label: "Solomon Islands", value: "SB" },
  { id: 159, label: "Somalia", value: "SO" },
  { id: 160, label: "South Africa", value: "ZA" },
  { id: 161, label: "South Sudan", value: "SS" },
  { id: 162, label: "Spain", value: "ES" },
  { id: 163, label: "Sri Lanka", value: "LK" },
  { id: 164, label: "Sudan", value: "SD" },
  { id: 165, label: "Suriname", value: "SR" },
  { id: 166, label: "Sweden", value: "SE" },
  { id: 167, label: "Switzerland", value: "CH" },
  { id: 168, label: "Syria", value: "SY" },
  { id: 169, label: "Taiwan", value: "TW" },
  { id: 170, label: "Tajikistan", value: "TJ" },
  { id: 171, label: "Tanzania", value: "TZ" },
  { id: 172, label: "Thailand", value: "TH" },
  { id: 173, label: "Timor-Leste", value: "TL" },
  { id: 174, label: "Togo", value: "TG" },
  { id: 175, label: "Tonga", value: "TO" },
  { id: 176, label: "Trinidad and Tobago", value: "TT" },
  { id: 177, label: "Tunisia", value: "TN" },
  { id: 178, label: "Turkey", value: "TR" },
  { id: 179, label: "Turkmenistan", value: "TM" },
  { id: 180, label: "Tuvalu", value: "TV" },
  { id: 181, label: "Uganda", value: "UG" },
  { id: 182, label: "Ukraine", value: "UA" },
  { id: 183, label: "United Arab Emirates", value: "AE" },
  { id: 184, label: "United Kingdom", value: "GB" },
  { id: 185, label: "United States", value: "US" },
  { id: 186, label: "Uruguay", value: "UY" },
  { id: 187, label: "Uzbekistan", value: "UZ" },
  { id: 188, label: "Vanuatu", value: "VU" },
  { id: 189, label: "Vatican City", value: "VA" },
  { id: 190, label: "Venezuela", value: "VE" },
  { id: 191, label: "Vietnam", value: "VN" },
  { id: 192, label: "Yemen", value: "YE" },
  { id: 193, label: "Zambia", value: "ZM" },
  { id: 194, label: "Zimbabwe", value: "ZW" }
] as const;


export const SOCIAL_PLATFORMS = [
  {
    name: "Facebook",
    regex: /facebook\.com/i,
    icon: <FacebookIcon className="size-4 text-blue-600" />,
  },
  {
    name: "Twitter",
    regex: /twitter\.com/i,
    icon: <TwitterIcon className="size-4 text-blue-400" />,
  },
  {
    name: "LinkedIn",
    regex: /linkedin\.com/i,
    icon: <Linkedin className="size-4 text-blue-700" />,
  },
  {
    name: "Instagram",
    regex: /instagram\.com/i,
    icon: <InstagramIcon className="size-4 text-pink-500" />,
  },
];
